Vagrant.configure("2") do |config|
    # Usamos Ubuntu 22.04 (puedes cambiar la caja según necesites)
    config.vm.box = "ubuntu/jammy64"
  
    # Reenvío de puertos:
    # - 8069: Odoo
    # - 5432: PostgreSQL
    # - 5678: VsCode Debug
    config.vm.network "forwarded_port", guest: 8069, host: 8069
    config.vm.network "forwarded_port", guest: 5432, host: 5432
    config.vm.network "forwarded_port", guest: 5678, host: 5678
  
    # Sincronización de archivos y carpetas:
    # Se sincroniza la carpeta ODOO y el archivo docker-compose.yml desde el host. Excluyendo presentaciones
    config.vm.synced_folder ".", "/home/vagrant/OdooSetup", type: "virtualbox", exclude: ["presentaciones"]
  
    # Provisionamiento: Instalación de Docker y Docker Compose
    config.vm.provision "shell", inline: <<-SHELL
      # Actualizar repositorios
      sudo apt-get update

      # Configurar fs.inotify.max_user_watches para evitar errores si se tienen muchos módulos
      sudo sysctl fs.inotify.max_user_watches=524288
      echo "fs.inotify.max_user_watches=524288" | sudo tee -a /etc/sysctl.conf
  
      # Instalar dependencias necesarias para Docker
      sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  
      # Añadir clave GPG oficial de Docker
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  
      # Añadir repositorio estable de Docker
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get update
  
      # Instalar Docker CE, CLI y containerd
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io
  
      # Instalar Docker Compose (versión 2.20.2, puedes actualizarla según necesites)
      sudo curl -L "https://github.com/docker/compose/releases/download/2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
  
      # Agregar el usuario vagrant al grupo docker para evitar usar 'sudo' al ejecutar docker
      sudo usermod -aG docker vagrant

      # Permisos necesarios para postgres
      sudo chown -R 999:999 /home/vagrant/OdooSetup/ODOO/data
      
    SHELL
  end
  