#version: '3'
services:
  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  odoo:
    image: odoo:16
    container_name: odoo
    environment:
      - HOST=${HOST}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
    ports:
      - '8069:8069'
    volumes:
      - ./ODOO/addons:/mnt/extra-addons
      - ./ODOO/filestore:/var/lib/odoo/filestore
    depends_on:
      - db
    command: odoo --workers=5 # Óptimo cálculo de workers: (CPU cores × 2) + 1
volumes:
  db_data:
